version: '3'

services:
  ###> symfony/mailer ###
  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --hide-extensions STARTTLS
    ports:
      - "1080:1080"
      - "1025:1025"
###< symfony/mailer ###
